### ISSUE TITLE
Fix 'MAINTAINER is deprecated' issue in docker\Dockerfile

### ISSUE THREAD

**Issue by mrasif** [tech-thinker/go-cookiecutter#4]
[CodeFactor](https://www.codefactor.io/repository/github/tech-thinker/go-cookiecutter/overview/main) found an issue: MAINTAINER is deprecated

It's currently on:
[docker\Dockerfile:2
](https://www.codefactor.io/repository/github/tech-thinker/go-cookiecutter/source/main/docker/Dockerfile#L2)

**Comment by mrinjamul** [comment]
replace `MAINTAINER "Asif Mohammad Mollah <admin@mrasif.in>"` with this  `LABEL maintainer="Asif Mohammad Mollah <admin@mrasif.in>"` . @mrasif

**Comment by mrasif** [comment]
Use label name 'Tech Thinker'

**Comment by mrinjamul** [comment]
email address will be empty ? or what?

**Comment by mrasif** [comment]
Use GitHub url of tech thinker organization.

**Comment by mrasif** [comment]
Resolved.
